force-app/main/default/objects/giic_JMSIntegrationMapping__mdt/giic_JMSIntegrationMapping__mdt.object-meta.xml
<CustomObject>
    <label>JMS Integration Mapping</label>
    <pluralLabel>JMS Integration Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/giic_JMSIntegrationMapping__mdt/fields/giic_CLIENT_KEY__c.field-meta.xml
<CustomField>
    <fullName>giic_CLIENT_KEY__c</fullName>
    <label>CLIENT KEY</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/giic_JMSIntegrationMapping__mdt/fields/giic_CLIENT_SECRET__c.field-meta.xml
<CustomField>
    <fullName>giic_CLIENT_SECRET__c</fullName>
    <label>CLIENT SECRET</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/giic_JMSIntegrationMapping__mdt/fields/giic_OAUTH_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>giic_OAUTH_Endpoint__c</fullName>
    <label>OAUTH Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/giic_getFedexOauthToken.cls
public class giic_getFedexOauthToken {
    
    public static string getAccessToken(giic_JMSIntegrationMapping__mdt jmsIntAttr) {
        
    
        String ENDPOINT = jmsIntAttr.giic_OAUTH_Endpoint__c;  // FedEx authorization API endpoint           
        String CLIENT_ID = jmsIntAttr.giic_CLIENT_KEY__c;       // JMS FedEx client ID    
        String CLIENT_SECRET = jmsIntAttr.giic_CLIENT_SECRET__c; // JMS FedEx client secret
        
        // Build the request body
        String requestBody = 'grant_type=client_credentials&client_id=' + CLIENT_ID + '&client_secret=' + CLIENT_SECRET;
        
        // Create the HTTP request
        HttpRequest request = new HttpRequest();
        request.setEndpoint(ENDPOINT);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        request.setBody(requestBody);
        
        // Send the HTTP request
        Http http = new Http();
        HttpResponse response = http.send(request);
        
        // Parse the response body and extract the token
        Map<String, Object> responseBody = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
        String token = (String)responseBody.get('access_token');
        
        system.debug('token' + token);
        
        return token;
        
    }    
}