force-app/main/default/objects/JMS_Broker_Call_Staging__c/JMS_Broker_Call_Staging__c.object-meta.xml
<CustomObject>
    <label>Broker Call Staging</label>
    <nameField>
        <displayFormat>BS-{000000000}</displayFormat>
        <label>Broker Call Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Call Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Account_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>JMS_Account_Error_Message__c</fullName>
    <description>All the Account error messages will be stored in this field</description>
    <label>Account Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Account_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Account_SF_Id__c</fullName>
    <label>Account SF Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Campaign_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Campaign_SF_Id__c</fullName>
    <label>Campaign SF Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Address__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Address__c</fullName>
    <description>Company Address</description>
    <label>Company Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Broker_Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Broker_Territory_Id__c</fullName>
    <description>Company Broker Territory Id</description>
    <label>Company Broker Territory Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Broker_Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Broker_Territory_Name__c</fullName>
    <description>Company Broker Territory Name</description>
    <label>Company Broker Territory Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_City__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_City__c</fullName>
    <description>City</description>
    <label>Company City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Country__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Country__c</fullName>
    <label>Company Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Name__c</fullName>
    <description>Company Name</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Phone__c</fullName>
    <description>company_phone</description>
    <label>Company Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_State__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_State__c</fullName>
    <description>Company State</description>
    <label>Company State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Zip__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Zip__c</fullName>
    <description>Zip Code</description>
    <label>Company Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_Email__c</fullName>
    <description>Email Id</description>
    <label>Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_First_Name__c</fullName>
    <description>Name</description>
    <label>Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_Last_Name__c</fullName>
    <description>Last Name</description>
    <label>Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_Phone__c</fullName>
    <description>Phone</description>
    <label>Contact Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Contact_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_SF_Id__c</fullName>
    <description>Will hold the existing Contact SF ID found with the Fuzzy Match</description>
    <label>Contact SF Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Product_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Product_SF_Id__c</fullName>
    <label>Product SF Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Record_Processed__c.field-meta.xml
<CustomField>
    <fullName>JMS_Record_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Record Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Status__c.field-meta.xml
<CustomField>
    <fullName>JMS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JMS_MigFromStagingToSObjectsBatchTest.cls
/**
* @description       : Test Class for JMS_Delete_SObject_RecordsTest
* @author            : Krishna
* @date              : 31/03/2022
* @last modified on  : 31/03/2021
* @last modified by  : Krishna
*/
@isTest
private class JMS_MigFromStagingToSObjectsBatchTest {
    public static final String STR_LIST_IS_NOT_NULL = 'List is not Null';
    public static final String STR_b001 = 'b001';
    public static final String STR_SUCCESS = 'Success';
    static testMethod void executeBatch(){
		JMS_Broker_Call_Staging__c stgObj = JMS_TestDataFactory.createBrokerCallStagingObj();
        stgObj.JMS_Record_Processed__c = FALSE;
        update stgObj;
        //Update broker call staging record
        List<JMS_Broker_Call_Staging__c> stgObjList = new List<JMS_Broker_Call_Staging__c>();
        stgObjList.add(stgObj);
        //List of broker call staging record
        //Start Test
        Test.startTest();
        JMS_MigrateBrokerCallStgnToSObject ba= new JMS_MigrateBrokerCallStgnToSObject();
        Database.executeBatch(ba);
        System.assert(stgObjList.size()>0,STR_LIST_IS_NOT_NULL);
        Test.stopTest();
        //Stop Test
        
    }//End of method
    
    static testMethod void executeBatch1(){
        Account accRec = JMS_TestDataFactory.createAccountByName('name');
        //Creating Account Record
        Contact conRec = JMS_TestDataFactory.createContact('name', accRec.Id);
        //Creating Contact Record
        Product2 prdRec = JMS_TestDataFactory.createProduct();
        //Creating Product Record
        Campaign campRec = JMS_TestDataFactory.createCampaign('name');
        //Creating Campaign Record
        campRec.Description = 'Test Camp 01';
        JMS_Broker_Call_Staging__c stgObj = JMS_TestDataFactory.createBrokerCallStagingObj();
        stgObj.JMS_Record_Processed__c = FALSE;
        stgObj.JMS_Batch_Id__c = STR_b001;
        stgObj.JMS_Status__c = STR_SUCCESS;
        stgObj.JMS_Campaign_SF_Id__c = '1234';
        stgObj.JMS_Account_SF_Id__c = '45655';// accRec.Id;
        stgObj.JMS_Company_Id__c = '1235';
        stgObj.JMS_Contact_SF_Id__c = conRec.Id;
        stgObj.JMS_Product_SF_Id__c = prdRec.Id;
        
        update stgObj;
        //Update broker call staging record
        List<JMS_Broker_Call_Staging__c> stgObjList = new List<JMS_Broker_Call_Staging__c>();
        stgObjList.add(stgObj);
        //List of broker call staging record
        //Start Test
        Test.startTest();
        JMS_MigrateBrokerCallStgnToSObject ba= new JMS_MigrateBrokerCallStgnToSObject(STR_b001);
        Database.executeBatch(ba);
        System.assert(stgObjList.size()>0,STR_LIST_IS_NOT_NULL);
        Test.stopTest();
        //Stop Test
        
    } 
    
        static testMethod void executeBatch2(){
            JMS_Broker_Call_Staging__c stgObj = JMS_TestDataFactory.createBrokerCallStagingObj();
            stgObj.JMS_Record_Processed__c = FALSE;
            stgObj.JMS_Batch_Id__c = STR_b001;
            stgObj.JMS_Status__c = 'Error';
            stgObj.JMS_Account_Error_Message__c = '123851';
            update stgObj;
            //Update broker call staging record
            List<JMS_Broker_Call_Staging__c> stgObjList = new List<JMS_Broker_Call_Staging__c>();
        	stgObjList.add(stgObj);
            //List of broker call staging record
            //Start Test
            Test.startTest();
            JMS_MigrateBrokerCallStgnToSObject ba= new JMS_MigrateBrokerCallStgnToSObject(STR_b001);
            Database.executeBatch(ba);
            System.assert(stgObjList.size()>0,STR_LIST_IS_NOT_NULL);
            Test.stopTest();
            //Stop Test
        
    } 
    
    static testMethod void executeBatch3(){
        JMS_Broker_Call_Staging__c stgObj = JMS_TestDataFactory.createBrokerCallStagingObj();
        stgObj.JMS_Record_Processed__c = FALSE;
        stgObj.JMS_Batch_Id__c = STR_b001;
        stgObj.JMS_Company_Type__c = 'Operator';
        stgObj.JMS_Status__c = STR_SUCCESS;
        stgObj.JMS_Company_Address__c = 'Test Address';
            stgObj.JMS_Company_Broker_Territory_Id__c = '456565'; 
            stgObj.JMS_Company_Broker_Territory_Name__c = 'Territory Name';
            stgObj.JMS_Company_City__c = 'New York City';
            stgObj.JMS_Company_Country__c = 'United States';
            stgObj.JMS_Company_Id__c = '34342';
            stgObj.JMS_Company_Name__c = 'Test Name';
            stgObj.JMS_Company_Phone__c = '1234567980';
            stgObj.JMS_Company_State__c = 'New York';
            stgObj.JMS_Company_Zip__c = '4532';
      
        update stgObj;
        //Update broker call staging record
        List<JMS_Broker_Call_Staging__c> stgObjList = new List<JMS_Broker_Call_Staging__c>();
        stgObjList.add(stgObj);
        //List of broker call staging record
        //Start Test
        Test.startTest();
        JMS_MigrateBrokerCallStgnToSObject ba= new JMS_MigrateBrokerCallStgnToSObject(STR_b001);
        Database.executeBatch(ba);
        System.assert(stgObjList.size()>0,STR_LIST_IS_NOT_NULL);
        Test.stopTest();
        //Stop Test
        
    } 
    static testMethod void executeBatch4(){
        JMS_Broker_Call_Staging__c stgObj = JMS_TestDataFactory.createBrokerCallStagingObj();
        stgObj.JMS_Record_Processed__c = FALSE;
        stgObj.JMS_Batch_Id__c = STR_b001;

        stgObj.JMS_Status__c = STR_SUCCESS;
        stgObj.JMS_Company_Address__c = 'Test Address';
            stgObj.JMS_Company_Broker_Territory_Id__c = '2476665'; 
            stgObj.JMS_Company_Broker_Territory_Name__c = 'Territory Name';
            stgObj.JMS_Company_City__c = 'New York City';
            stgObj.JMS_Company_Country__c = 'United States';
            stgObj.JMS_Company_Id__c = '23445';
            stgObj.JMS_Company_Name__c = 'Test Name';
            stgObj.JMS_Company_Phone__c = '1234567980';
            stgObj.JMS_Company_State__c = 'New York';
            stgObj.JMS_Company_Zip__c = '345654342';
      
        update stgObj;
        //Update broker call staging record
        List<JMS_Broker_Call_Staging__c> stgObjList = new List<JMS_Broker_Call_Staging__c>();
        stgObjList.add(stgObj);
        //List of broker call staging record
        //Start Test
        Test.startTest();
        JMS_MigrateBrokerCallStgnToSObject ba= new JMS_MigrateBrokerCallStgnToSObject(STR_b001);
        Database.executeBatch(ba);
        System.assert(stgObjList.size()>0,STR_LIST_IS_NOT_NULL);
        Test.stopTest();
        //Stop Test
        
    } 
    
    //Error with Account name missing
    static testMethod void executeBatch5(){
        JMS_Broker_Call_Staging__c stgObj = JMS_TestDataFactory.createBrokerCallStagingObj();
        stgObj.JMS_Record_Processed__c = FALSE;
        stgObj.JMS_Batch_Id__c = STR_b001;
        
        stgObj.JMS_Status__c = STR_SUCCESS;
        stgObj.JMS_Company_Broker_Territory_Id__c = '34565'; 
        stgObj.JMS_Company_Broker_Territory_Name__c = 'Territory Name';
        stgObj.JMS_Company_City__c = 'New York City';
        stgObj.JMS_Company_Country__c = 'United States';
        stgObj.JMS_Company_Id__c = '8765';
        stgObj.JMS_Company_Phone__c = '1234567980';
        stgObj.JMS_Company_State__c = 'New York';
        stgObj.JMS_Company_Zip__c = '12345';
        stgObj.JMS_Contact_Email__c = 'ss@dd.com';
        stgObj.JMS_Contact_First_Name__c = 'fname';
        stgObj.JMS_Contact_Last_Name__c = 'lname';
        stgObj.JMS_Contact_Phone__c = '123456790';
        
        update stgObj;
        //Update broker call staging record
        List<JMS_Broker_Call_Staging__c> stgObjList = new List<JMS_Broker_Call_Staging__c>();
        stgObjList.add(stgObj);
        //List of broker call staging record
        //Start Test
        Test.startTest();
        JMS_MigrateBrokerCallStgnToSObject ba= new JMS_MigrateBrokerCallStgnToSObject(STR_b001);
        Database.executeBatch(ba);
        System.assert(stgObjList.size()>0,STR_LIST_IS_NOT_NULL);
        Test.stopTest();
        //Stop Test
        
    } 
}