force-app/main/default/objects/JMS_Broker_Call_Landing__c/JMS_Broker_Call_Landing__c.object-meta.xml
<CustomObject>
    <label>Broker Call Landing</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Broker Call Landing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Call Landings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Batch_Id__c</fullName>
    <description>To capture Batch Id</description>
    <label>Batch Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Broker_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Broker_Name__c</fullName>
    <description>JMS_Broker_Name__c</description>
    <label>Broker Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Call_Distributor_Code__c.field-meta.xml
<CustomField>
    <fullName>JMS_Call_Distributor_Code__c</fullName>
    <description>Call Distributor Code</description>
    <label>Call Distributor Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Call_Status__c.field-meta.xml
<CustomField>
    <fullName>JMS_Call_Status__c</fullName>
    <description>Call Status</description>
    <label>Call Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Company_Address__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Address__c</fullName>
    <description>Company Address</description>
    <label>Company Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Company_Broker_Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Broker_Territory_Id__c</fullName>
    <description>Broker Territory Id</description>
    <label>Company Broker Territory Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Company_Broker_Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Broker_Territory_Name__c</fullName>
    <description>Broker Territory Name</description>
    <label>Company Broker Territory Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Company_City__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_City__c</fullName>
    <description>Company City</description>
    <label>Company City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Company_Country__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Country__c</fullName>
    <label>Company Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Id__c</fullName>
    <description>Company Id</description>
    <label>Company Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Name__c</fullName>
    <description>Company Name</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Company_State__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_State__c</fullName>
    <description>Company State</description>
    <label>Company State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Company_Type__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Type__c</fullName>
    <description>Company Type</description>
    <label>Company Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Company_Zip__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Zip__c</fullName>
    <description>Company Zip</description>
    <label>Company Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_Email__c</fullName>
    <description>Contact Email</description>
    <label>Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_First_Name__c</fullName>
    <description>Contact First Name</description>
    <label>Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_Last_Name__c</fullName>
    <description>Contact Last Name</description>
    <label>Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Item_No_Sale_Reason__c.field-meta.xml
<CustomField>
    <fullName>JMS_Item_No_Sale_Reason__c</fullName>
    <description>Item No Sale Reason</description>
    <label>Item No Sale Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Item_No_Sale_Reason_Detail__c.field-meta.xml
<CustomField>
    <fullName>JMS_Item_No_Sale_Reason_Detail__c</fullName>
    <description>Item No Sale Reason Detail</description>
    <label>Item No Sale Reason Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>JMS_Opportunity_Stage__c</fullName>
    <description>Opportunity Stage</description>
    <label>Opportunity Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Landing__c/fields/JMS_Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>JMS_Unique_Key__c</fullName>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/JMS_Broker_Call_Staging__c.object-meta.xml
<CustomObject>
    <label>Broker Call Staging</label>
    <nameField>
        <displayFormat>BS-{000000000}</displayFormat>
        <label>Broker Call Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Call Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Account_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>JMS_Account_Error_Message__c</fullName>
    <description>All the Account error messages will be stored in this field</description>
    <label>Account Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Account_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Account_SF_Id__c</fullName>
    <label>Account SF Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Broker_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Broker_Name__c</fullName>
    <description>Broker Name</description>
    <label>Broker Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Call_distributor_code__c.field-meta.xml
<CustomField>
    <fullName>JMS_Call_distributor_code__c</fullName>
    <description>Call Distributor Code</description>
    <label>Call Distributor Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Campaign_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Campaign_SF_Id__c</fullName>
    <label>Campaign SF Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Address__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Address__c</fullName>
    <description>Company Address</description>
    <label>Company Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Broker_Territory_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Broker_Territory_Id__c</fullName>
    <description>Company Broker Territory Id</description>
    <label>Company Broker Territory Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Broker_Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Broker_Territory_Name__c</fullName>
    <description>Company Broker Territory Name</description>
    <label>Company Broker Territory Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_City__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_City__c</fullName>
    <description>City</description>
    <label>Company City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Country__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Country__c</fullName>
    <label>Company Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Name__c</fullName>
    <description>Company Name</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Phone__c</fullName>
    <description>company_phone</description>
    <label>Company Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_SF_Id__c</fullName>
    <description>Company SF Id</description>
    <label>Company SF Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_State__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_State__c</fullName>
    <description>Company State</description>
    <label>Company State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Company_Zip__c.field-meta.xml
<CustomField>
    <fullName>JMS_Company_Zip__c</fullName>
    <description>Zip Code</description>
    <label>Company Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_Email__c</fullName>
    <description>Email Id</description>
    <label>Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_First_Name__c</fullName>
    <description>Name</description>
    <label>Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_Last_Name__c</fullName>
    <description>Last Name</description>
    <label>Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Contact_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>JMS_Contact_SF_Id__c</fullName>
    <description>Will hold the existing Contact SF ID found with the Fuzzy Match</description>
    <label>Contact SF Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Item_No_Sale_Reason__c.field-meta.xml
<CustomField>
    <fullName>JMS_Item_No_Sale_Reason__c</fullName>
    <description>Item No Sale Reason</description>
    <label>Item No Sale Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Kickout_Failed_Reason__c.field-meta.xml
<CustomField>
    <fullName>JMS_Kickout_Failed_Reason__c</fullName>
    <label>Kickout Failed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Kickout_Location__c.field-meta.xml
<CustomField>
    <fullName>JMS_Kickout_Location__c</fullName>
    <label>Kickout Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Opportunity_stage__c.field-meta.xml
<CustomField>
    <fullName>JMS_Opportunity_stage__c</fullName>
    <description>Stage of Opportunity</description>
    <label>Opportunity Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Record_Processed__c.field-meta.xml
<CustomField>
    <fullName>JMS_Record_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Record Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Status__c.field-meta.xml
<CustomField>
    <fullName>JMS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call_Staging__c/fields/JMS_Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>JMS_Unique_Key__c</fullName>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/JMS_MigrateBrokerCallStgnToSObjectTest.cls
/**
* @description       : Test Class for JMS_MigrateBrokerCallStgnToSObjectTest
* @author            : Krishna
* @date              : 31/03/2022
* @last modified on  : 31/03/2021
* @last modified by  : Krishna
*/
//Start
 @isTest
private class JMS_MigrateBrokerCallStgnToSObjectTest {
    
     
    static testMethod void executeBatchTest0(){
        JMS_Broker_Call_Staging__c brokerCallObj = JMS_TestDataFactory.createBrokerCallStagingObj();
        brokerCallObj.JMS_Company_Address__c = '123 Main street';
        brokerCallObj.JMS_Company_City__c = 'New York City';
        brokerCallObj.JMS_Company_Country__c = 'United States';
        brokerCallObj.JMS_Company_Name__c = 'Sumit Textiles';
        brokerCallObj.JMS_Company_Phone__c = '1324567980';
        brokerCallObj.JMS_Company_State__c = 'New York';
        brokerCallObj.JMS_Account_Error_Message__c = '';
        brokerCallObj.JMS_Status__c = 'Error';
        brokerCallObj.JMS_Kickout_Failed_Reason__c = 'Hello World';
        brokerCallObj.JMS_Kickout_Location__c = 'Salesforce';
        brokerCallObj.JMS_Batch_Id__c = 'abcd';
        brokerCallObj.JMS_Broker_Name__c = 'IAC';
        UPDATE brokerCallObj;
        //Start Test
        Test.startTest();
        JMS_MigrateBrokerCallStgnToSObject ba= new JMS_MigrateBrokerCallStgnToSObject('abcd');
        Database.executeBatch(ba);
        System.assert(brokerCallObj !=null,'Object is not Null');
        Test.stopTest();
        //Stop Test
    }    
    //Start Test
    static testMethod void executeBatchTest(){
        //Creating Account records
        Account acct = JMS_TestDataFactory.createAccountByName('TestAccount');
        //Contact con = JMS_TestDataFactory.createContact('Test Primary Contact' , acct.Id);
        
        //Creating Campaign Records
        Campaign camp = JMS_TestDataFactory.createCampaign('Test Campaign');
        list<Product2> prdlist = JMS_TestDataFactory.createProductRecds(1);
        JMS_Broker_Call_Staging__c brokerCallObj = JMS_TestDataFactory.createBrokerCallStagingObj();
        //brokerCallObj.JMS_Line_Product_Id__c = prdlist[0].Id;
        
        brokerCallObj.JMS_Campaign_SF_Id__c = camp.Id;
        brokerCallObj.JMS_Kickout_Failed_Reason__c = Null;
        brokerCallObj.JMS_Record_Processed__c = false;
        brokerCallObj.JMS_Status__c = 'SUCCESS';
        brokerCallObj.JMS_Company_Type__c = 'Distributor';
        //brokerCallObj.JMS_Account_SF_Id__c = acct.Id;
        brokerCallObj.JMS_Company_SF_Id__c = acct.Id;
        brokerCallObj.JMS_Company_Broker_Territory_Name__c = 'FREEMAN QUEBEC';
        brokerCallObj.JMS_Company_Broker_Territory_Id__c = '90784';
        brokerCallObj.JMS_Company_Zip__c = '06777';
        brokerCallObj.JMS_Company_State__c = 'FLorida';
        brokerCallObj.JMS_Company_City__c = 'eklrewlfkerwf';
        brokerCallObj.JMS_Company_Address__c = 'wkjrhjkewr';
        brokerCallObj.JMS_Company_Id__c = 'w98374893';
        brokerCallObj.JMS_Company_Name__c = 'TEST FINALTEST94';         
        brokerCallObj.JMS_Contact_Email__c = 'SS@DD.com';
        brokerCallObj.JMS_Contact_First_Name__c = 'Arnold';
        brokerCallObj.JMS_Contact_Last_Name__c = 'S';
        Update brokerCallObj;
        
        //Start test
        Test.startTest();
        JMS_MigrateBrokerCallStgnToSObject ba= new JMS_MigrateBrokerCallStgnToSObject();
        Database.executeBatch(ba);
        System.assert(brokerCallObj !=null,'Object is not Null');
        Test.stopTest();
        //Stop Test
    }//End
    
    static testMethod void executeBatchBadTest(){
        //Creating Account records
        Account acct = JMS_TestDataFactory.createAccountByName('TestAccount');
        //Creating Contact Records
        Contact con = JMS_TestDataFactory.createContact('Test Primary Contact' , acct.Id);
        //Creating Campaign Records
        Campaign camp = JMS_TestDataFactory.createCampaign('TestCampaign');
        list<Product2> prdlist = JMS_TestDataFactory.createProductRecds(1);
        //Creating Product Record
        JMS_Broker_Call_Staging__c brokerCallObj = JMS_TestDataFactory.createBrokerCallStagingObj();
        //brokerCallObj.JMS_Line_Product_Id__c = prdlist[0].Id;
        brokerCallObj.JMS_Account_SF_Id__c = acct.Id;
        brokerCallObj.JMS_Contact_SF_Id__c = con.Id;
        brokerCallObj.JMS_Campaign_SF_Id__c = camp.Id;
        brokerCallObj.JMS_Kickout_Failed_Reason__c = Null;
        brokerCallObj.JMS_Record_Processed__c = false;
        brokerCallObj.JMS_Status__c = 'SUCCESS';
        brokerCallObj.JMS_Company_Type__c = 'Distributor';
        brokerCallObj.JMS_Company_SF_Id__c = acct.Id;
        brokerCallObj.JMS_Company_Broker_Territory_Name__c = 'FREEMAN QUEBEC';
        brokerCallObj.JMS_Company_Broker_Territory_Id__c = '90784';
        brokerCallObj.JMS_Company_Zip__c = '06777';
        brokerCallObj.JMS_Company_State__c = 'FLorida';
        brokerCallObj.JMS_Company_City__c = 'eklrewlfkerwf';
        brokerCallObj.JMS_Company_Address__c = 'wkjrhjkewr';
        brokerCallObj.JMS_Company_Id__c = 'w98374893';
        brokerCallObj.JMS_Company_Name__c = 'TEST FINALTEST94';         
        Update brokerCallObj;
        //Updating Brokercall Staging
        //Start Test
        Test.startTest();
        JMS_MigrateBrokerCallStgnToSObject ba= new JMS_MigrateBrokerCallStgnToSObject();
        Database.executeBatch(ba);
        System.assert(brokerCallObj !=null,'Object is not Null');
        Test.stopTest();
        //Stop Test
    }//End 
    
    
    //Start Test
    static testMethod void executeBatchCatchTest(){
        //Creating Account records
        Account acct = JMS_TestDataFactory.createAccountByName('TestAccount');
        //Contact con = JMS_TestDataFactory.createContact('Test Primary Contact' , acct.Id);
        
        //Creating Campaign Records
        Campaign camp = JMS_TestDataFactory.createCampaign('Test Campaign');
        
        list<Product2> prdlist = JMS_TestDataFactory.createProductRecds(1);
        JMS_Broker_Call_Landing__c brkCallLand = JMS_TestDataFactory.createBrokerCallStaging();
        brkCallLand.JMS_Call_Distributor_Code__c = '211';
        brkCallLand.JMS_Batch_Id__c = 'b001';
        brkCallLand.JMS_Unique_Key__c = 'DistributorSS@DD.com';
        brkCallLand.JMS_Company_Broker_Territory_Name__c = 'FREEMAN QUEBEC';
        brkCallLand.JMS_Company_Broker_Territory_Id__c = '90784';
        brkCallLand.JMS_Item_No_Sale_Reason__c = 'Test';
        brkCallLand.JMS_Item_No_Sale_Reason_Detail__c = 'Test';
        brkCallLand.JMS_Opportunity_Stage__c = 'Test';
        brkCallLand.JMS_Company_Type__c = 'Test';
        brkCallLand.JMS_Call_Status__c = 'Test';
        Update brkCallLand;
        JMS_Broker_Call_Staging__c brokerCallObj = JMS_TestDataFactory.createBrokerCallStagingObj();
        //brokerCallObj.JMS_Line_Product_Id__c = prdlist[0].Id;
        
        brokerCallObj.JMS_Campaign_SF_Id__c = camp.Id;
        brokerCallObj.JMS_Kickout_Failed_Reason__c = Null;
        brokerCallObj.JMS_Record_Processed__c = false;
        brokerCallObj.JMS_Status__c = 'SUCCESS';
        brokerCallObj.JMS_Company_Type__c = 'Distributor';
        //brokerCallObj.JMS_Account_SF_Id__c = acct.Id;
        brokerCallObj.JMS_Company_SF_Id__c = acct.Id;
        brokerCallObj.JMS_Company_Broker_Territory_Name__c = 'FREEMAN QUEBEC';
        brokerCallObj.JMS_Company_Broker_Territory_Id__c = '90784';
        brokerCallObj.JMS_Company_Zip__c = '06777';
        brokerCallObj.JMS_Company_State__c = '';
        brokerCallObj.JMS_Unique_Key__c = 'DistributorSS@DD.com';
        brokerCallObj.JMS_Company_City__c = 'eklrewlfkerwf';
        brokerCallObj.JMS_Company_Address__c = 'wkjrhjkewr';
        brokerCallObj.JMS_Company_Id__c = 'w98374893';
        brokerCallObj.JMS_Company_Name__c = 'TEST FINALTEST94';         
        brokerCallObj.JMS_Contact_Email__c = 'SS@DD.com';
        brokerCallObj.JMS_Contact_First_Name__c = 'Arnold';
        brokerCallObj.JMS_Contact_Last_Name__c = 'S';
        Update brokerCallObj;
        
        //Start test
        Test.startTest();
        JMS_MigrateBrokerCallStgnToSObject ba= new JMS_MigrateBrokerCallStgnToSObject();
        Database.executeBatch(ba);
        System.assert(brokerCallObj !=null,'Object is not Null');
        Test.stopTest();
        //Stop Test
    }//End
}