force-app/main/default/objects/JMS_Territory_Assignment__c/JMS_Territory_Assignment__c.object-meta.xml
<CustomObject>
    <description>This will store the copy of the ObjectTerritory2Association records.</description>
    <label>Territory Assignment</label>
    <nameField>
        <displayFormat>TA-{00000}</displayFormat>
        <label>Territory Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JMS_Territory_Assignment__c/fields/JMS_ZipCodeAssignment__c.field-meta.xml
<CustomField>
    <fullName>JMS_ZipCodeAssignment__c</fullName>
    <description>It will store zipcode value.</description>
    <label>ZipCode</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JMS_TerritoryAssignmentTriggerHelperTest.cls
/**
* @description       : Test Class for JMS_Delete_SObject_RecordsTest
* @author            : Krishna
* @date       		 : 31/03/2022
* @last modified on  : 31/03/2021
* @last modified by  : Krishna
*/
@Istest
private class JMS_TerritoryAssignmentTriggerHelperTest {
    @IsTest
    private static void clearAccountTerritoryTest(){
        User userName = JMS_TestDataFactory.createAdminUser();
        Territory2Model terrModel = JMS_TestDataFactory.createTerritory2Model();
        Territory2 terr = JMS_TestDataFactory.createTerritory(terrModel.Id);
        System.runAs(userName){
            //Create Account Record
            Account acc = JMS_TestDataFactory.createAccountByName('Test Account');
            Opportunity opp = JMS_TestDataFactory.createOpportunity('Test Opportunity',acc.Id);
            opp.Description = 'Test';
            JMS_Territory_Assignment__c terrAssig = JMS_TestDataFactory.createJMSTeritoryAssignment(terr.Id,acc.Id);
            terrAssig.JMS_ZipCodeAssignment__c = '12112';
            UPDATE terrAssig;
            Map<Id,JMS_Territory_Assignment__c> mapIdVsTerriAssig = NEW Map<Id,JMS_Territory_Assignment__c>();
            mapIdVsTerriAssig.put(terrAssig.Id, terrAssig);
            //Delete Territory
            DELETE terrAssig;
            //UnDelete Territory
            UNDELETE terrAssig;
            //Start Test
            Test.startTest();
            JMS_TerritoryAssignmentTriggerHelper helper = new JMS_TerritoryAssignmentTriggerHelper();
            JMS_TerritoryAssignmentTriggerHandler handler = new JMS_TerritoryAssignmentTriggerHandler();
            String trigName = handler.getName();
            JMS_TerritoryAssignmentTriggerHelper.clearAccountTerritory(mapIdVsTerriAssig);
            System.assertEquals('JMS_Territory_Assignment__c', trigName,'trigName is not Null');
            //Stop Test
            Test.stopTest();
    	}
	}
}