force-app/main/default/objects/JMS_ZipCodes__c/JMS_ZipCodes__c.object-meta.xml
<CustomObject>
    <description>It will Store all the Zip COdes with Territory Details.</description>
    <label>ZipCodes</label>
    <nameField>
        <displayFormat>ZC-{00000}</displayFormat>
        <label>ZipCode Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZipCodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JMS_ZipCodes__c/fields/JMS_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>JMS_Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It will check that the zipcode is Active or not.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/JMS_AssignObjectTerritoryBatchTest.cls
/**
* @description       : Test Class for JMS_Delete_SObject_RecordsTest
* @author            : Krishna
* @date       		 : 31/03/2022
* @last modified on  : 31/03/2021
* @last modified by  : Krishna
*/
@isTest
private class JMS_AssignObjectTerritoryBatchTest {
    static testMethod void executeBatchTest(){
        Account acct = JMS_TestDataFactory.createAccountByName('Test Account');
        List<Account> acclist = new List<Account>();
        acclist.add(acct);
        JMS_ZipCodes__c zipRecord = JMS_TestDataFactory.createZipcodes('Test zipcode');
        zipRecord.JMS_Is_Active__c = True;
        Test.startTest();
        JMS_AssignObjectTerritoryAssociatBatch ba= new JMS_AssignObjectTerritoryAssociatBatch();
        /*
         * Removed unused varibles - CodeScan Error
         * Anil - 3/6/2022 */
        Database.executeBatch(ba);
        ba.start(null);
        ba.execute(null,accList);
        ba.Finish(null);
        Test.stopTest();
        system.assertEquals(1,accList.size(),'accList is Null');
        
    }
}