force-app/main/default/objects/ProcessSteps__mdt/ProcessSteps__mdt.object-meta.xml
<CustomObject>
    <description>Contains the steps for processes</description>
    <label>ProcessStep</label>
    <pluralLabel>ProcessSteps</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProcessSteps__mdt/fields/Page_Name__c.field-meta.xml
<CustomField>
    <fullName>Page_Name__c</fullName>
    <label>Page Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessSteps__mdt/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <label>Process</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessSteps__mdt/fields/Step_Name__c.field-meta.xml
<CustomField>
    <fullName>Step_Name__c</fullName>
    <label>Step Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessSteps__mdt/fields/Step_Number__c.field-meta.xml
<CustomField>
    <fullName>Step_Number__c</fullName>
    <label>Step Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AppController.cls
public with sharing class AppController {
    /*
    @AuraEnabled
    public static String getUserAccount(){
        User user = [select Id, Name, ContactId from User where Id = :UserInfo.getUserId() LIMIT 1];
        Contact con = [Select Id, AccountId from Contact Where Id = :user.ContactId];
        return con.AccountId;
    }
    */
    @AuraEnabled
    public static String getUserType(){        
        return UserInfo.getUserType();
    }
    
    @AuraEnabled
    public static Map<String, Object> getStages(String processName){        
        String strProcessName = (String)processName;
        System.debug('strProcessName:::' + strProcessName);
        List<ProcessStepsWrapper> psMD = new List<ProcessStepsWrapper>();
        for(ProcessSteps__mdt ps :[SELECT Id, Active__c, Process__c, Page_Name__c, Step_Name__c, Step_Number__c FROM ProcessSteps__mdt WHERE Active__c =: true AND Process__c =: strProcessName ORDER BY Step_Number__c ASC]){
            ProcessStepsWrapper pr = new ProcessStepsWrapper();
            pr.Active = ps.Active__c;
            pr.Process = ps.Process__c;
            pr.Page_Name = ps.Page_Name__c;
            pr.Step_Name = ps.Step_Name__c;
            pr.Step_Number = ps.Step_Number__c;
            psMD.add(pr);    
        }
        
        Map<String, Object> mp = new Map<String, Object>();
        mp.put('ProcessSteps', psMD);
        String userType = getUserType();
        if(userType.equalsIgnoreCase('Standard')){            
            mp.put('isExternalUser', false);
        } 
        else{
            //String accountId = getUserAccount();
            mp.put('isExternalUser', true);
            //mp.put('accountId', accountId);
        } 
        SalesOrderUtil.deleteSO(null);
        return mp;
    }
}