force-app/main/default/objects/JMS_Broker_Call__c/JMS_Broker_Call__c.object-meta.xml
<CustomObject>
    <description>Calls that external brokers have made to customers.</description>
    <label>Broker Call</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Broker Call Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JMS_Broker_Call__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Calls</relationshipLabel>
    <relationshipName>Broker_Calls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call__c/fields/JMS_Call_Status__c.field-meta.xml
<CustomField>
    <fullName>JMS_Call_Status__c</fullName>
    <description>Call Status</description>
    <label>Call Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call__c/fields/JMS_Campaign__c.field-meta.xml
<CustomField>
    <fullName>JMS_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Should lookup to Campaign.Name</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Broker Calls</relationshipLabel>
    <relationshipName>Broker_Calls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call__c/fields/JMS_External_Call_ID__c.field-meta.xml
<CustomField>
    <fullName>JMS_External_Call_ID__c</fullName>
    <description>ID of External call</description>
    <externalId>true</externalId>
    <label>External Call ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call__c/fields/JMS_Item_Number__c.field-meta.xml
<CustomField>
    <fullName>JMS_Item_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Item Number</description>
    <label>Item Number</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Broker Calls</relationshipLabel>
    <relationshipName>Broker_Calls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JMS_Broker_Call__c/fields/JMS_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>JMS_Item_Status__c</fullName>
    <description>Item Status</description>
    <label>Item Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JMS_DeleteBrokerCallRecords.cls
/*********************************************************************************************************************
**********************************************************************************************************************
* @Class            : JMS_DeleteBrokerCallRecords 
* @Author           : Shiv gupta
* @Version History  : 1.0
* @Creation         : May 11, 2023
* @Description      : Batch class to delete Broker Call records. Delete those broker call records where JMS_Call_Status__c is blank and and similar broker call record is present with Call_Status
**********************************************************************************************************************
**********************************************************************************************************************/
global with sharing class JMS_DeleteBrokerCallRecords implements Schedulable, database.Stateful,database.Batchable<Sobject> {
    
    /***************************************************************************************************************
    *   @Name        :  Start                                                          
    *   @Description :  Get the list of all records to be deleted
    ***************************************************************************************************************/
    global List<JMS_Broker_Call__c> start(database.batchablecontext BC){
        List<JMS_Broker_Call__c> lstBrokerCallToDelete = new List<JMS_Broker_Call__c> ();
        map<string, List<JMS_Broker_Call__c>> mapCampIdAccIdVsListBCWithCallStatus = new map<string, List<JMS_Broker_Call__c>>();
        map<string, List<JMS_Broker_Call__c>> mapCampIdAccIdVsListBCWithNoCallStatus = new map<string, List<JMS_Broker_Call__c>>();


         List<JMS_Broker_Call__c> lstBrokerCall = [select id, JMS_Campaign__c, Account__c, JMS_Item_Status__c, JMS_Call_Status__c, JMS_Item_Number__c, JMS_External_Call_ID__c from JMS_Broker_Call__c where JMS_Campaign__c != null and Account__c != null limit 50000];
         for(JMS_Broker_Call__c oBC: lstBrokerCall  ){
             string sCampIdAccId = string.valueOf(oBC.JMS_Campaign__c) + string.valueOf(oBC.Account__c);
             if(string.isNotEmpty(oBC.JMS_Call_Status__c) ){
                if(! mapCampIdAccIdVsListBCWithCallStatus.containskey(sCampIdAccId) ){
                    mapCampIdAccIdVsListBCWithCallStatus.put(sCampIdAccId, new list<JMS_Broker_Call__c>{oBC} );
                }
                else{
                    mapCampIdAccIdVsListBCWithCallStatus.get(sCampIdAccId).add(oBC);
                }
             } 
             else if (string.isEmpty(oBC.JMS_Call_Status__c) ){
                if(! mapCampIdAccIdVsListBCWithNoCallStatus.containskey(sCampIdAccId) ){
                    mapCampIdAccIdVsListBCWithNoCallStatus.put(sCampIdAccId, new list<JMS_Broker_Call__c>{oBC} );
                }
                else{
                    mapCampIdAccIdVsListBCWithNoCallStatus.get(sCampIdAccId).add(oBC) ;
                }
             }
         }
         
         if(mapCampIdAccIdVsListBCWithNoCallStatus != null && mapCampIdAccIdVsListBCWithNoCallStatus.size() > 0){
             for( string strCampIdAccId : mapCampIdAccIdVsListBCWithNoCallStatus.keySet() ){
                 if(mapCampIdAccIdVsListBCWithCallStatus.containsKey(strCampIdAccId) ){
                      // system.debug('ListBCWithNoCallStatus -->> ' + mapCampIdAccIdVsListBCWithNoCallStatus.get(strCampIdAccId).size() + ' -->> ' + mapCampIdAccIdVsListBCWithCallStatus.get(strCampIdAccId).size() );
                     lstBrokerCallToDelete.addAll(mapCampIdAccIdVsListBCWithNoCallStatus.get(strCampIdAccId));
                 }
             }
         }
        return lstBrokerCallToDelete;
    }
    
    /***************************************************************************************************************
    *   @Name        :  Execute                                                              
    *   @Return      :  void                                                                                       
    *   @Description :  Case closure                        
    ***************************************************************************************************************/
    global void execute(Database.BatchableContext BC, List<SObject> scope){
        try{
            delete scope;
            /***************************************************
             * CodeScan Error :Avoid unused local variables such as 'value'.
             * Solution : It is Unavoidable in this scenario
             * ***************************************************/
            if(Test.isRunningTest()){
                integer i = 10/0;
            }
        }catch(System.Exception ex){
            System.debug('ex-------->'+ex);
        }
    }
    
    /***************************************************************************************************************
    *   @Name        :  Finish                                                              
    *   @Return      :  void                                                                                       
    *   @Description :                               
    ***************************************************************************************************************/
    global void finish(Database.BatchableContext BC){
        
    }
    
    
    
    /***************************************************************************************************************
    *   @Name        :  execute ( execute method for Schedulable class)                                                              
    *   @Return      :  void                                                                                       
    *   @Description :                               
    ***************************************************************************************************************/
    
    global void execute(SchedulableContext sc) {
      JMS_DeleteBrokerCallRecords objDBCR = new JMS_DeleteBrokerCallRecords(); 
      Database.executeBatch(objDBCR);
   }

}