force-app/main/default/objects/JMS_Log_Config__c/JMS_Log_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to manage the custom logging using Logger framework</description>
    <label>JMS Log Config</label>
</CustomObject>

force-app/main/default/objects/JMS_Log_Config__c/fields/JMS_Debug_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>JMS_Debug_Record_Type__c</fullName>
    <description>This is the name of the record type which is used to present debug information on the log object.</description>
    <label>Debug Record Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Log_Config__c/fields/JMS_Exception_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>JMS_Exception_Record_Type__c</fullName>
    <description>This is the name of the record type which is used to present exception information on the log object</description>
    <label>Exception Record Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Log_Config__c/fields/JMS_Exceptions_Enabled__c.field-meta.xml
<CustomField>
    <fullName>JMS_Exceptions_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is a flag to denote if exceptions should be logged to the database</description>
    <label>Exceptions Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JMS_Log_Config__c/fields/JMS_Logging_Enabled__c.field-meta.xml
<CustomField>
    <fullName>JMS_Logging_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is a flag to denote if debug information should be logged to the database</description>
    <label>Logging Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/JMS_LoggerTest.cls
@Istest 
public class JMS_LoggerTest {
    //Start
	@IsTest
    private static void createTraceFlagTest(){
        //User salesUser = JMS_TestDataFactory.createUser();
        /*system.runAs(salesUser){
            
        }*/
        //Logger Test
        
        JMS_Log_Config__c configObj = new JMS_Log_Config__c();
        configObj.JMS_Debug_Record_Type__c = 'Debug';
        configObj.JMS_Exception_Record_Type__c = 'Exception';
        configObj.JMS_Exceptions_Enabled__c = TRUE;
        configObj.JMS_Logging_Enabled__c = TRUE;
        insert configObj;
        
        //JMS_Log_Config__c configInstance = JMS_Log_Config__c.getInstance(UserInfo.getUserId());
        //Account Creation
        Account acct = JMS_TestDataFactory.createAccountByName('test Account');
        acct.Description = 'Test';
        //System assertion
        String trigName = 'Test assert';
        System.assertEquals('Test assert', trigName,'trigName is not Null');
    }//End
}