force-app/main/default/objects/JMS_Log__c/JMS_Log__c.object-meta.xml
<CustomObject>
    <description>This is the log entity that stores information about system errors that may be encountered while the system is running.</description>
    <label>SF Inbound &amp; Exception Log</label>
    <nameField>
        <displayFormat>LOG-{000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF Inbound &amp; Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JMS_Log_Config__c/JMS_Log_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to manage the custom logging using Logger framework</description>
    <label>JMS Log Config</label>
</CustomObject>

force-app/main/default/objects/JMS_Log_Config__c/fields/JMS_Debug_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>JMS_Debug_Record_Type__c</fullName>
    <description>This is the name of the record type which is used to present debug information on the log object.</description>
    <label>Debug Record Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Log_Config__c/fields/JMS_Exception_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>JMS_Exception_Record_Type__c</fullName>
    <description>This is the name of the record type which is used to present exception information on the log object</description>
    <label>Exception Record Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JMS_Log_Config__c/fields/JMS_Exceptions_Enabled__c.field-meta.xml
<CustomField>
    <fullName>JMS_Exceptions_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is a flag to denote if exceptions should be logged to the database</description>
    <label>Exceptions Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JMS_Log_Config__c/fields/JMS_Logging_Enabled__c.field-meta.xml
<CustomField>
    <fullName>JMS_Logging_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is a flag to denote if debug information should be logged to the database</description>
    <label>Logging Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/JMS_LogConfigSettings.cls
/*******************************************************************************

* @description  Class that is used to retrieve the LogConfig custom settings of 
*               the current user profile. 
*******************************************************************************/
public class JMS_LogConfigSettings {
    
    private static JMS_Log_Config__c theSetting = JMS_Log_Config__c.getInstance(UserInfo.getUserId());
    
    private static Map<string, schema.recordtypeinfo> recordTypeInfo = Schema.getGlobalDescribe().get('JMS_Log__c').getDescribe().getRecordTypeInfosByName();
    
    
    public static Id getDebugRecordType(){
        
        if(recordTypeInfo.get(theSetting.JMS_Debug_Record_Type__c)!=null){
            
            return recordTypeInfo.get(theSetting.JMS_Debug_Record_Type__c).getRecordTypeId();
            
        }
        else{
            
            return null; 
            
        }  
        
    }
    
    
    public static Id getExceptionRecordType(){
        
        if(recordTypeInfo.get(theSetting.JMS_Exception_Record_Type__c)!=null){
            
            return recordTypeInfo.get(theSetting.JMS_Exception_Record_Type__c).getRecordTypeId();
            
        }
        else{
            
            return null; 
            
        }    
    }
    
    public static  Boolean loggingEnabled(){
        
        return theSetting.JMS_Logging_Enabled__c;
    }
    public static  Boolean exceptionEnabled(){
        
        return theSetting.JMS_Exceptions_Enabled__c;
    }
}