force-app/main/default/objects/giic_IntegrationMapping__mdt/giic_IntegrationMapping__mdt.object-meta.xml
<CustomObject>
    <description>This Object is used to create mapping of fields of source sobject to fields of target sobject</description>
    <label>Integration Mapping</label>
    <pluralLabel>Integration Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/giic_IntegrationMapping__mdt/fields/giic_ExternalField__c.field-meta.xml
<CustomField>
    <fullName>giic_ExternalField__c</fullName>
    <description>External Field API of Sobject</description>
    <label>External Field</label>
    <metadataRelationshipControllingField>giic_IntegrationMapping__mdt.giic_ExternalSObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Integration_Mappings</relationshipLabel>
    <relationshipName>Integration_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/giic_IntegrationMapping__mdt/fields/giic_IsDataTypeCheck__c.field-meta.xml
<CustomField>
    <fullName>giic_IsDataTypeCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDataTypeCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/giic_IntegrationMapping__mdt/fields/giic_SourceField__c.field-meta.xml
<CustomField>
    <fullName>giic_SourceField__c</fullName>
    <description>Select Source Field API</description>
    <label>Source Field</label>
    <metadataRelationshipControllingField>giic_IntegrationMapping__mdt.giic_SourceObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Integration Details Source Field</relationshipLabel>
    <relationshipName>IntegrationDetailsSourceField</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/giic_IntegrationMapping__mdt/fields/giic_SourceObject__c.field-meta.xml
<CustomField>
    <fullName>giic_SourceObject__c</fullName>
    <description>Select Source Object</description>
    <label>Source Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Integration Details Source Object</relationshipLabel>
    <relationshipName>IntegrationDetailsSourceObject</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/giic_IntegrationMapping__mdt/fields/giic_TargetField__c.field-meta.xml
<CustomField>
    <fullName>giic_TargetField__c</fullName>
    <description>Select Target Sobject Field</description>
    <label>Target Field</label>
    <metadataRelationshipControllingField>giic_IntegrationMapping__mdt.giic_TargetObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Integration Details Target Field</relationshipLabel>
    <relationshipName>IntegrationDetailsTargetField</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/giic_IntegrationMapping__mdt/fields/giic_TargetObject__c.field-meta.xml
<CustomField>
    <fullName>giic_TargetObject__c</fullName>
    <description>Select Target Sobject</description>
    <label>Target Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Integration Details Target Object</relationshipLabel>
    <relationshipName>IntegrationDetailsTargetObject</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/giic_integrationWrapper.cls
public class giic_integrationWrapper {
    public String sourceSobject {get;set;}
    public String targetSobject {get;set;}
    public String targetField {get;set;}
    public String sourceField {get;set;}
    public Boolean dataTypeField {get;set;}
    public giic_IntegrationMapping__mdt wrapperInstance{get;set;}
	public static List<giic_integrationWrapper> getWrapperList(String sourceObj, String targetObj){ //Add param source and target obj
		List<giic_integrationWrapper> lstMetaData = new List<giic_integrationWrapper>();
        //[Select giic_ExternalField__r.QualifiedApiName,giic_SourceObject__r.QualifiedApiName,giic_SourceField__r.QualifiedApiName,
        //giic_TargetObject__r.QualifiedApiName, giic_TargetField__r.QualifiedApiName From giic_IntegrationMapping__mdt Where giic_SourceObject__r.QualifiedApiName =: sourceObj AND giic_TargetObject__r.QualifiedApiName =: targetObj ]); //Put Soql query with filter as source and target obj
		for(giic_IntegrationMapping__mdt objMetaData : [Select giic_SourceObject__r.QualifiedApiName,giic_SourceField__r.DataType,giic_SourceField__r.QualifiedApiName,giic_TargetObject__r.QualifiedApiName,
                                                        giic_TargetField__r.QualifiedApiName,giic_IsDataTypeCheck__c From giic_IntegrationMapping__mdt Where giic_SourceObject__r.QualifiedApiName =: sourceObj AND giic_TargetObject__r.QualifiedApiName =: targetObj]){ //Use lstMetaData
			giic_integrationWrapper wrapperObj = new giic_integrationWrapper();
			wrapperObj.sourceSobject = objMetaData.giic_SourceObject__r.QualifiedApiName;
			wrapperObj.targetSobject = objMetaData.giic_TargetObject__r.QualifiedApiName;
			wrapperObj.targetField = objMetaData.giic_TargetField__r.QualifiedApiName;
			wrapperObj.sourceField = objMetaData.giic_SourceField__r.QualifiedApiName;
            wrapperObj.dataTypeField = objMetaData.giic_IsDataTypeCheck__c;
			system.debug('objMetaData>>>>2'+wrapperObj);
			wrapperObj.wrapperInstance = objMetaData;                                               
			system.debug('objMetaData>>>>3'+wrapperObj.wrapperInstance);
			lstMetaData.add(wrapperObj);
		}
		if(lstMetaData.size() > 0)
			return lstMetaData;
		else
			return null;
	}
}